---@meta khoma

-- Auto-generated by `go run ./cmd/khomadoc` from internal/docgen/meta.go.
-- Do not edit by hand — edit the source table and regenerate.

---@alias khoma.Edge "top"|"bottom"|"left"|"right"

---@class khoma.AnimateSpec
---@field duration number?
---@field easing string?
---@field props string[]?

---@class khoma.Element

---@class khoma.Component
---@overload fun(props: table?): khoma.Element

---@class khoma.Store
---@field get fun(self: khoma.Store): any
---@field set fun(self: khoma.Store, value: any)

---@alias khoma.Canvas.Command table -- {op="rect"|"circle"|"arc"|"line"|"polygon"|"text", ...}; see docs/reference.md#canvas

---@class khoma.App
---@field id string
---@field name string
---@field description string
---@field icon string

-- Hooks -----------------------------------------------------------------

--- Wraps a render function as a reusable component. `Counter { ... }` (calling the result) produces an
--- element — a lazy description expanded later once its path-based identity is known, which is what
--- makes hook state and hot reload work.
---@param nameOrFn string|(fun(props: table?): khoma.Element|khoma.Element[]|nil)
---@param fn (fun(props: table?): khoma.Element|khoma.Element[]|nil)?
---@return khoma.Component
function component(nameOrFn, fn) end

--- Component-local state, identity-keyed so it survives hot reload. The setter accepts either a new
--- value or an updater `function(prev) return next end`; updates are batched and coalesced into one
--- render.
---@generic T
---@param initial T
---@return T value
---@return fun(next: T|fun(prev: T): T) setter
function useState(initial) end

--- A stable mutable box that does not trigger re-renders when written.
---@generic T
---@param initial T
---@return { current: T } ref
function useRef(initial) end

--- Caches `fn()`'s result until `deps` changes (shallow compare: scalars by value, tables/functions by
--- reference).
---@generic T
---@param fn fun(): T
---@param deps table?
---@return T
function useMemo(fn, deps) end

--- Runs `fn` after the render pass commits, when `deps` changed (every render if `deps` is omitted,
--- once if `deps` is `{}`). `fn` may return a cleanup function, run before the next execution and on
--- unmount.
---@param fn fun(): (fun()|nil)
---@param deps table?
function useEffect(fn, deps) end

--- Calls `fn` every `ms` milliseconds; cancelled automatically on unmount. `fn` is re-bound every
--- render, so it never closes over stale state.
---@param fn fun()
---@param ms number
function useInterval(fn, ms) end

--- Calls `fn` once after `ms` milliseconds; cancelled automatically on unmount if it hasn't fired yet.
---@param fn fun()
---@param ms number
function useTimeout(fn, ms) end

--- Subscribes to a Go-backed store (a khoma.Store global such as `Battery` or `Screens`) and re-renders
--- when it changes. An optional selector narrows re-renders to when the *selected* value changes.
---@generic T
---@param store khoma.Store
---@param selector (fun(value: any): T)?
---@return T
function useStore(store, selector) end

--- A Lua-granularity animated number: when `target` changes, the returned value tweens toward it at the
--- configured fps, re-rendering the component each tick. For per-frame animation with zero Lua work,
--- use the `animate` widget prop instead.
---@param target number
---@param opts { duration: number?, easing: string?, fps: number? }?
---@return number
function useAnimatedValue(target, opts) end

--- Like useState, but the initial value is read from (and every update written to) a JSON file on disk
--- keyed by AppID, so it survives process restart. `key` is a plain string the caller picks — two
--- instances sharing a key intentionally share state, same contract as browser localStorage.
---@generic T
---@param key string
---@param initial T
---@return T value
---@return fun(next: T|fun(prev: T): T) setter
function usePersistent(key, initial) end

-- Widgets ---------------------------------------------------------------

---@class khoma.WindowProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field title string? Default "khoma".
---@field width number? Default size (480×360 if both omitted).
---@field height number? Default size.
---@field resizable boolean? 
---@field decorated boolean? Show the compositor's server-side decorations.
---@field clickThrough boolean? Makes the mapped window ignore all pointer input (empty input region). All-or-nothing; sticky for the window's lifetime.
---@field onClose fun()? Fired on a close request; khoma still lets GTK close the window afterward.

--- A plain toplevel application window. Takes exactly one child.
---@param props khoma.WindowProps?
---@return khoma.Element
function Window(props) end

---@class khoma.PanelWindowProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field screen string? Output connector (e.g. "DP-1"); omit to let the compositor pick.
---@field anchor khoma.Edge|khoma.Edge[]? Edges to anchor to: any of "top"|"bottom"|"left"|"right".
---@field exclusive boolean|number? true reserves the surface's natural size; a number reserves that many px; false/omitted reserves nothing.
---@field layer "background"|"bottom"|"top"|"overlay"? Default "top".
---@field keyboard "none"|"on-demand"|"exclusive"? Keyboard focus mode. Default "none".
---@field namespace string? layer-shell namespace, for compositor rules. Default "khoma".
---@field margins {top: number?, bottom: number?, left: number?, right: number?}? Exclusive-zone-relative margins per anchored edge.

--- A layer-shell surface (bars, docks, OSDs, wallpaper layers). Requires a Wayland compositor with
--- wlr-layer-shell; falls back to a plain window (logged) otherwise.
---@param props khoma.PanelWindowProps?
---@return khoma.Element
function PanelWindow(props) end

---@class khoma.LockSurfaceProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field screen string? Output connector this surface is bound to.

--- A session-lock surface for one monitor, rendered while the `Locked` store is true. See
--- khoma.session/khoma.auth.
---@param props khoma.LockSurfaceProps?
---@return khoma.Element
function LockSurface(props) end

---@class khoma.ColumnProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field spacing number? Pixels between children.
---@field homogeneous boolean? Give every child equal size.

--- Vertical box layout.
---@param props khoma.ColumnProps?
---@return khoma.Element
function Column(props) end

---@class khoma.RowProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field spacing number? Pixels between children.
---@field homogeneous boolean? Give every child equal size.

--- Horizontal box layout.
---@param props khoma.RowProps?
---@return khoma.Element
function Row(props) end

---@class khoma.BoxProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field orientation "horizontal"|"vertical"? Default "vertical".
---@field spacing number? Pixels between children.
---@field homogeneous boolean? Give every child equal size.

--- Generic styled container (the `Rectangle` equivalent — background/radius/border via `style`),
--- vertical unless `orientation` says otherwise.
---@param props khoma.BoxProps?
---@return khoma.Element
function Box(props) end

---@class khoma.GridProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field rowSpacing number? 
---@field columnSpacing number? 

--- Grid layout; children position via the row/column/rowSpan/colSpan layout props.
---@param props khoma.GridProps?
---@return khoma.Element
function Grid(props) end

---@class khoma.FixedProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.

--- Absolute-position layout; children position via the x/y layout props.
---@param props khoma.FixedProps?
---@return khoma.Element
function Fixed(props) end

---@class khoma.StackProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.

--- Overlay stack: the first child is the base, later children stack visually on top of it (GtkOverlay).
---@param props khoma.StackProps?
---@return khoma.Element
function Stack(props) end

---@class khoma.ScrollableProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field hscroll "auto"|"always"|"never"|"external"? Default "auto".
---@field vscroll "auto"|"always"|"never"|"external"? Default "auto".

--- Scrolling viewport for a single child.
---@param props khoma.ScrollableProps?
---@return khoma.Element
function Scrollable(props) end

---@class khoma.RevealerProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field transition "none"|"crossfade"|"slide-right"|"slide-left"|"slide-up"|"slide-down"? 
---@field duration number? Transition duration in ms. Default 250.
---@field revealed boolean? Whether the child is currently shown.

--- Animated show/hide for a single child.
---@param props khoma.RevealerProps?
---@return khoma.Element
function Revealer(props) end

---@class khoma.PaddingProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field children khoma.Element[]? Positional children (or an explicit array) are laid out by this container.
---@field all number? Shorthand for all four sides; overridden per-side below.
---@field top number? 
---@field bottom number? 
---@field left number? 
---@field right number? 

--- Wraps a child (or children, box-laid-out) with margins.
---@param props khoma.PaddingProps|string?
---@return khoma.Element
function Padding(props) end

---@class khoma.SpacerProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.

--- An empty box that expands to fill leftover space (hexpand/vexpand default true, unlike other
--- widgets).
---@param props khoma.SpacerProps?
---@return khoma.Element
function Spacer(props) end

---@class khoma.SeparatorProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field orientation "horizontal"|"vertical"? Default "horizontal".

--- A thin dividing line.
---@param props khoma.SeparatorProps?
---@return khoma.Element
function Separator(props) end

---@class khoma.TextProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field text string? 
---@field markup boolean? Interpret `text` as Pango markup.
---@field wrap boolean? 
---@field ellipsize "none"|"start"|"middle"|"end"? 

--- A text label.
---@param props khoma.TextProps|string?
---@return khoma.Element
function Text(props) end

---@class khoma.ButtonProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field label string? 
---@field onClick fun()? 

--- A clickable button.
---@param props khoma.ButtonProps|string?
---@return khoma.Element
function Button(props) end

---@class khoma.TextFieldProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field text string? 
---@field placeholder string? 
---@field onChange fun(text: string)? 

--- A single-line text entry. `text` is a controlled prop: khoma only writes the GTK buffer when it
--- differs from what's already shown, so re-renders from onChange don't clobber the caret.
---@param props khoma.TextFieldProps|string?
---@return khoma.Element
function TextField(props) end

---@class khoma.CheckBoxProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field label string? 
---@field checked boolean? 
---@field onToggle fun(active: boolean)? 

--- A labeled checkbox.
---@param props khoma.CheckBoxProps|string?
---@return khoma.Element
function CheckBox(props) end

---@class khoma.SwitchProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field active boolean? 
---@field onToggle fun(state: boolean)? Return true from the handler to veto the visual state change (rarely needed).

--- An on/off toggle.
---@param props khoma.SwitchProps?
---@return khoma.Element
function Switch(props) end

---@class khoma.SliderProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field min number? Default 0.
---@field max number? Default 100.
---@field value number? 
---@field orientation "horizontal"|"vertical"? 
---@field drawValue boolean? Show the numeric value on the slider.
---@field onChange fun(value: number)? 

--- A draggable range slider (GtkScale).
---@param props khoma.SliderProps|string?
---@return khoma.Element
function Slider(props) end

---@class khoma.ProgressBarProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field fraction number? 0–1.

--- A progress indicator.
---@param props khoma.ProgressBarProps|string?
---@return khoma.Element
function ProgressBar(props) end

---@class khoma.ImageProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field source string? File path.
---@field fit "fill"|"contain"|"cover"|"scale-down"? 

--- A raster image loaded from a file path.
---@param props khoma.ImageProps|string?
---@return khoma.Element
function Image(props) end

---@class khoma.IconProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field width number? Requested width in pixels (-1/omitted = natural size).
---@field height number? Requested height in pixels (-1/omitted = natural size).
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field icon string? Icon theme name, e.g. "audio-volume-high-symbolic".
---@field size number? Pixel size. Default 16.

--- A themed icon (GtkIconTheme lookup by name).
---@param props khoma.IconProps|string?
---@return khoma.Element
function Icon(props) end

---@class khoma.CanvasProps
---@field key string? Stable identity within a keyed list of siblings; required whenever siblings can reorder, be inserted, or removed.
---@field class string? Space-separated CSS class names, styled by the app's style.css (hot-reloaded).
---@field style table? Inline style table, compiled to a scoped CSS rule: {background="#222", border_radius=8, padding="4px 8px", [":hover"]={...}}. Underscored keys become dashed CSS properties; numbers become px.
---@field animate boolean|khoma.AnimateSpec? Tweens any changed numeric prop on the GTK frame clock (zero per-frame Lua). true animates every numeric prop; a table restricts to `props` and sets `duration`/`easing`.
---@field hexpand boolean? Expand horizontally to fill available space.
---@field vexpand boolean? Expand vertically to fill available space.
---@field halign "fill"|"start"|"center"|"end"? Horizontal alignment within the parent's allocation.
---@field valign "fill"|"start"|"center"|"end"? Vertical alignment within the parent's allocation.
---@field margin number? Uniform margin in pixels on all four sides.
---@field opacity number? 0–1.
---@field visible boolean? Default true.
---@field tooltip string? Tooltip text shown on hover.
---@field disabled boolean? Marks the widget insensitive (GTK's SetSensitive(false)).
---@field cursor string? GTK cursor name, e.g. "pointer", "grab".
---@field onPress fun(button: number, x: number, y: number, nPress: number)? Pointer button pressed.
---@field onRelease fun(button: number, x: number, y: number, nPress: number)? Pointer button released.
---@field onHover fun(entered: boolean)? Pointer entered/left the widget's allocation.
---@field onMotion fun(x: number, y: number)? Pointer moved within the widget.
---@field onScroll fun(dx: number, dy: number)? Scroll wheel/touchpad input.
---@field width number? 
---@field height number? 
---@field commands khoma.Canvas.Command[]? rect | circle | arc | line | polygon | text — see the type alias for each op's fields.

--- Imperative 2D drawing as pure data: Lua emits a command list, Go replays it onto cairo on redraw. An
--- unchanged `commands` table (deep-equal) redraws nothing. See khoma.Canvas.Command below for the op
--- vocabulary.
---@param props khoma.CanvasProps?
---@return khoma.Element
function Canvas(props) end

-- Modules (require("khoma.xxx")) -----------------------------------------

---@class khoma.process
---@field exec fun(cmd: string|string[], cb: (fun(out: string, code: number))?) One-shot: collect stdout, call cb(out, exitcode).
---@field spawn fun(argv: string|string[], opts: { onLine: (fun(line: string))?, onStderr: (fun(line: string))?, onExit: (fun(code: number))? }?): { stop: fun(), pid: number } Long-running: line-streamed callbacks; returns a handle.

---@class khoma.file
---@field read fun(path: string): string?, err: string?
---@field write fun(path: string, data: string): ok: boolean?, err: string?
---@field exists fun(path: string): boolean
---@field list fun(dir: string): string[]?, err: string?
---@field watch fun(path: string, cb: fun(content: string), intervalMs: number?): fun() stop Fires cb(content) whenever the file's mtime changes (and once immediately).

---@class khoma.json
---@field decode fun(str: string): any?, err: string?
---@field encode fun(value: any): string?, err: string?

---@class khoma.env
---@field get fun(name: string): string?
---@field home fun(): string
---@field config_dir fun(): string $XDG_CONFIG_HOME or ~/.config.
---@field data_dir fun(): string $XDG_DATA_HOME or ~/.local/share.
---@field cache_dir fun(): string $XDG_CACHE_HOME or ~/.cache.
---@field hostname fun(): string

---@class khoma.clipboard
---@field set fun(text: string)
---@field get fun(cb: fun(text: string?)) text is nil when the clipboard is empty/unavailable.

---@class khoma.ipc
---@field register fun(name: string, fn: fun(...: any): any) The handler's single return value round-trips to the CLI caller as JSON.

---@class khoma.notifications
---@field close fun(id: number) Dismiss, as if the user closed it.
---@field invoke_action fun(id: number, key: string) Fire an action button.

---@class khoma.media
---@field play_pause fun(busName: string)
---@field next fun(busName: string)
---@field previous fun(busName: string)
---@field stop fun(busName: string)

---@class khoma.hyprland
---@field dispatch fun(cmd: string): ok: boolean, output: string Runs a `hyprctl dispatch`-style command, e.g. dispatch("workspace 2").

---@class khoma.audio
---@field set fun(level: number) 0–1.
---@field set_muted fun(muted: boolean)

---@class khoma.brightness
---@field set fun(percent: number) 0–100.

---@class khoma.apps
---@field list fun(): khoma.App[] Refreshes and returns the cache filter()/launch() read from.
---@field filter fun(query: string): khoma.App[] Substring match against the cache from the last list() call.
---@field launch fun(id: string)

---@class khoma.session
---@field supported fun(): boolean
---@field lock fun()
---@field unlock fun()
---@field is_locked fun(): boolean
---@field on_failed fun(cb: fun()) Called when the compositor refuses a lock attempt (the session was NOT locked; the `Locked` store does not flip).

---@class khoma.auth
---@field check fun(service: string?, password: string, cb: fun(ok: boolean, reason: string?)) service defaults to "login".

-- Other globals -----------------------------------------------------------

--- khoma's config-facing API version (semver string), for authors who need to branch on capability
--- across khoma releases. See ui/version.go.
---@type string
KHOMA_VERSION = nil

-- Stores (globals; use with useStore) ------------------------------------

--- Connected outputs (GdkMonitor list), hotplug-aware. { name, model, x, y, width, height, scale }[].
---@type khoma.Store
Screens = nil

--- UPower DisplayDevice, PropertiesChanged-driven (no polling). { present, percentage, state, icon,
--- timeToEmpty, timeToFull }.
---@type khoma.Store
Battery = nil

--- wpctl-backed, polled.
---@type khoma.Store
Volume = nil

--- sysfs-read, polled.
---@type khoma.Store
Brightness = nil

--- Hyprland workspaces. { id, name, monitor, windows }[].
---@type khoma.Store
Workspaces = nil

--- Hyprland clients. { address, class, title, workspaceId, floating, fullscreen }[].
---@type khoma.Store
Clients = nil

--- Hyprland active window.
---@type khoma.Store
ActiveWindow = nil

--- MPRIS players. { busName, identity, status, title, artist, album, artUrl, length, volume, canPlay,
--- canPause, canGoNext, canGoPrevious }[].
---@type khoma.Store
Players = nil

--- Active notifications this session's server holds. { id, appName, appIcon, summary, body, actions,
--- urgency }[].
---@type khoma.Store
Notifications = nil

--- Whether the session-lock instance currently holds the compositor lock.
---@type khoma.Store
Locked = nil

