# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun


exec-once=waybar
exec-once=hypridle
exec-once=nm-applet --indicator
exec-once=blueman-applet
exec-once=swaync
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
