# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = nmrs
    match:class = org.nmrs.ui

    float = true
}

windowrule {
    name = nwg-displays
    match:class = ^(nwg-displays)$

    float = true
    center = true
}

windowrule {
    name = blueman-manager
    match:class = ^(blueman-manager)$

    float = true
    opacity = 0.80 0.70
}

windowrule {
    name = nm-applet
    match:class = ^(nm-connection-editor)$

    float = yes
    opacity = 0.80 0.70
}
