source = ~/.config/hypr/themes/mocha.conf

general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor =
    color = rgba($baseAlphaff)
    blur_passes = 3
    blur_size = 7
    brightness = 0.8
}

# Clock
label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba($textAlphaff)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 200
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = rgba($subtext1Alphaff)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 110
    halign = center
    valign = center
}

# Avatar
shape {
    monitor =
    size = 100, 100
    color = rgba($surface0Alphaff)
    rounding = -1
    border_size = 3
    border_color = rgba($mauveAlphaff)
    position = 0, 0
    halign = center
    valign = center
}

# Password input
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba($surface0Alphaff)
    inner_color = rgba($surface0Alphaff)
    font_color = rgba($textAlphaff)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    check_color = rgba($greenAlphaff)
    fail_color = rgba($redAlphaff)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgba($yellowAlphaff)
    rounding = 10
    position = 0, -120
    halign = center
    valign = center
}
