-- Generated by nwg-displays on 2026-06-15 at 08:59:59. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "3173x1728",
    scale = 1.07
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "2538x0",
    scale = 1.25
})
